theme: jekyll-theme-minimal

title: [Poolkeh]
description: [Optimizing Test-Pooling for COVID-19]


[GOTO Poolkeh](https://poolkeh.herokuapp.com/)
[https://poolkeh.herokuapp.com/](https://poolkeh.herokuapp.com/)


[![Watch the video](https://imgur.com/GeYuCnd)](https://www.youtube.com/watch?v=5GIrsYVs71c)

show_downloads: ["false"]
#google_analytics: [Your Google Analytics tracking ID]
